# -*- coding: utf-8 -*-
{
    'name': "Integration",
    'author': "Gold, mohammedabodahab401@gmail.com",
    'website': "",
    'category': '',
    'version': '0.1',
    'depends': ['base', 'sale', 'delivery', 'stock', 'account', 'product'],
    'data': [
        'data/cron_job.xml',
        'security/ir.model.access.csv',
        'views/res_company_view.xml',
        'views/sale_order_view.xml',
        'views/sale_order_logging_error_view.xml',
        'views/zone_view.xml',
        'views/delivery_carrier_view.xml',
        'views/stock_picking_batch_view.xml',
        'views/stock_picking_view.xml',
        'views/account_move.xml',
        'views/res_config_settings_view.xml',
        'views/product_product_view.xml',
        'report/paper_foramt.xml',
        'report/report_product_batch.xml',
        'report/product_batch_report_views.xml',
        'report/report_invoice.xml',
        'report/report_quotation.xml',
    ],
    'demo': [],
    'test': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3'
}
